runtime: python39  # Python runtime
entrypoint: uvicorn main:app --host=0.0.0.0 --port=8080

instance_class: F2  # Optional: Choose the instance class based on resources
env_variables:  # Optional: Set environment variables
  APP_ENV: "production"

automatic_scaling:  # Optional: Configure scaling
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.75
  max_instances: 5
